# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/73/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/73/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/DCC265A1C265809E/Uni/ООП/Практикум/DataBaseStudentsGrades

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/DCC265A1C265809E/Uni/ООП/Практикум/DataBaseStudentsGrades

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/73/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/73/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/DCC265A1C265809E/Uni/ООП/Практикум/DataBaseStudentsGrades/CMakeFiles /mnt/DCC265A1C265809E/Uni/ООП/Практикум/DataBaseStudentsGrades/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/DCC265A1C265809E/Uni/ООП/Практикум/DataBaseStudentsGrades/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Data_Base_Students_Grades

# Build rule for target.
Data_Base_Students_Grades: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Data_Base_Students_Grades
.PHONY : Data_Base_Students_Grades

# fast build rule for target.
Data_Base_Students_Grades/fast:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/build
.PHONY : Data_Base_Students_Grades/fast

Functions.o: Functions.cpp.o

.PHONY : Functions.o

# target to build an object file
Functions.cpp.o:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/Functions.cpp.o
.PHONY : Functions.cpp.o

Functions.i: Functions.cpp.i

.PHONY : Functions.i

# target to preprocess a source file
Functions.cpp.i:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/Functions.cpp.i
.PHONY : Functions.cpp.i

Functions.s: Functions.cpp.s

.PHONY : Functions.s

# target to generate assembly for a file
Functions.cpp.s:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/Functions.cpp.s
.PHONY : Functions.cpp.s

Student.o: Student.cpp.o

.PHONY : Student.o

# target to build an object file
Student.cpp.o:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/Student.cpp.o
.PHONY : Student.cpp.o

Student.i: Student.cpp.i

.PHONY : Student.i

# target to preprocess a source file
Student.cpp.i:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/Student.cpp.i
.PHONY : Student.cpp.i

Student.s: Student.cpp.s

.PHONY : Student.s

# target to generate assembly for a file
Student.cpp.s:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/Student.cpp.s
.PHONY : Student.cpp.s

StudentList.o: StudentList.cpp.o

.PHONY : StudentList.o

# target to build an object file
StudentList.cpp.o:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/StudentList.cpp.o
.PHONY : StudentList.cpp.o

StudentList.i: StudentList.cpp.i

.PHONY : StudentList.i

# target to preprocess a source file
StudentList.cpp.i:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/StudentList.cpp.i
.PHONY : StudentList.cpp.i

StudentList.s: StudentList.cpp.s

.PHONY : StudentList.s

# target to generate assembly for a file
StudentList.cpp.s:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/StudentList.cpp.s
.PHONY : StudentList.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Data_Base_Students_Grades.dir/build.make CMakeFiles/Data_Base_Students_Grades.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Data_Base_Students_Grades"
	@echo "... edit_cache"
	@echo "... Functions.o"
	@echo "... Functions.i"
	@echo "... Functions.s"
	@echo "... Student.o"
	@echo "... Student.i"
	@echo "... Student.s"
	@echo "... StudentList.o"
	@echo "... StudentList.i"
	@echo "... StudentList.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

